### ISSUE TITLE
Add chat.new functionality, with chat.check

### ISSUE THREAD

**Issue by scenaristeur** [scenaristeur/shighl#5]
From @Julian-Cole
In the UI i have added the ability to add new channels but only if they already exist in a Pod somewhere; it does no validation to whether the user has permission to post / read etc. The "Channel name" is the part url to the chat messages like.
https://solidarity/inrupt.net/solidarity

Or in the Shighl case where I created a containing folder so it would be possible to group related chats,  the "Channel Name" would be Shighl/Shighl 
  
I would like to perhaps show a green tick by validating the channel when they have typed in the channel details and clicked a "verify" button.  I'm not sure how possible that is ?

Should a channel have info like..
  Short description of Channel?
  Banner Picture for Channel?   like a Youtube channel banner  
  Owner of chat solid channel,  for admin / report purposes.

![image](https://user-images.githubusercontent.com/4020744/74822488-7d477b80-5305-11ea-8d92-359a8bf3a1c5.png)

**Comment by scenaristeur** [comment]
to test if a channel exist https://github.com/scenaristeur/shighl/blob/632beb5828975765368cfbe22df223b099850fdd/dist/instances.html#L192

**Comment by Julian-Cole** [comment]
hmm i tried to get that to work this morning,  i will have another try tonight.

**Comment by Julian-Cole** [comment]
ok sorted,  kind of! you will have to try it.  lol

**Comment by Julian-Cole** [comment]
i can;t close this issue

**Comment by scenaristeur** [comment]
Is it ok for you?
