### ISSUE TITLE
Prettyifying the chat text

### ISSUE THREAD

**Issue by scenaristeur** [scenaristeur/shighl#6]
From @Julian-Cole 
Hi,  I was thinking about the formatting of the text as it comes out the "messages.content"  to maybe copy the way Gitter formats the text, links pasted go blue, images etc?  code snipit? markdown?  emojis?
I was thinking it would useful if this happened in the API in a standard way rather than on multiple project code levels, as a basic feature of long-chat API.
.. but optional content format rather than compulsory

**Comment by scenaristeur** [comment]
we must take a look at https://easymde.tk/ but it's more an UI/editor issue, i think.
First the editor must implement Markdown

**Comment by Julian-Cole** [comment]
I've added "showdown" to the UI code so it doesn't really need to in Shighl

e.g in version 0.4

![image](https://user-images.githubusercontent.com/49248917/75830534-fdabb900-5da8-11ea-81e7-35371e35b32b.png)

**Comment by scenaristeur** [comment]
great !

**Comment by scenaristeur** [comment]
done
